.TH INTERNSCTL 1 "January 2023" "v0.1.0" "Internsctl Manual"
.SH NAME
internsctl \- Custom Linux command for operations

.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]... [\fIARGUMENT\fR]...

.SH DESCRIPTION
This manual page documents the internsctl command.

.SH OPTIONS
.TP
.BR \-\-help
Display help message.

.TP
.BR \-\-version
Display the version of the command.

.SH EXAMPLES
.PP
Display help:
.BR internsctl \-\-help

.PP
Show version:
.BR internsctl \-\-version

.SH AUTHOR
Your Name <your.email@example.com>

.SH SEE ALSO
man(1)
